# Generated by Django 4.1.2 on 2022-10-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('surname', models.CharField(blank=True, max_length=300)),
                ('tg_username', models.CharField(blank=True, max_length=255)),
                ('tg_id', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('bonus', models.IntegerField(blank=True)),
                ('phone_number', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('rating', models.FloatField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_list', models.CharField(blank=True, max_length=255)),
                ('address_to_deliver', models.CharField(blank=True, max_length=255)),
                ('is_delivered', models.BooleanField(blank=True, default=False)),
                ('is_pay', models.BooleanField(blank=True, default=False)),
                ('price', models.IntegerField(blank=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.profile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.IntegerField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.restaurant')),
            ],
        ),
    ]
