# Generated by Django 4.1.2 on 2022-10-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
