# Generated by Django 4.1.1 on 2022-10-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_profile_tg_id_alter_profile_tg_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
