# Generated by Django 4.1.2 on 2022-10-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_name_profile_full_name_remove_profile_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tg_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
