# Generated by Django 4.1.2 on 2022-10-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_order_restaurant_order_address_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
