# Generated by Django 4.1.2 on 2022-10-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_stuff_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_photos/%Y/%m/%d/', verbose_name='Фотографии'),
        ),
    ]
