# Generated by Django 4.1.2 on 2022-10-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_restaurant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tg_id',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Tg ID'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='profile',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Tg ID'),
        ),
    ]
