# Generated by Django 4.1.2 on 2022-10-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_profile_tg_id_alter_stuff_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ref_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Айди рефералки'),
        ),
    ]
